# Generated by Django 3.2.19 on 2023-11-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_alter_decompilationrequest_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompilation',
            name='request',
        ),
        # State-only removal: the composed index was never created at the DB
        # level (see migration 0015), so there is nothing to drop here. Keeping
        # the state operation keeps migration state consistent with the model.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterIndexTogether(
                    name='decompilationrequest',
                    index_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.RemoveField(
            model_name='decompilationrequest',
            name='completed',
        ),
    ]
